### PR TITLE
security fix

### PR DESCRIPTION
**Pull request by grdunn**

### CODE REVIEW

**Comment by abea** [comment]
Have you tested that this still works fine? We have a few projects this is in already.

My only comment looking at this is to ignore the lock file.

**Comment by grdunn** [comment]
I've tested this on GDI, and appears to work fine.

**Review by abea — APPROVED** [review]
Bless you.

**Review by stuartromanek — APPROVED** [review]

**Review by abea — CHANGES_REQUESTED** [review]
The version number should bump the patch level and URLs in package.json should change from `punkave` to `apostrophecms`.

**Review by abea — APPROVED** [review]

**Pull request merged**
